query GetComments(
    $postId: ID,
    $contentFilterBy: ContentFilterType,
    $offset: Int,
    $limit: Int
) {
    listPosts(
        postid: $postId,
        contentFilterBy: $contentFilterBy
        commentLimit: $limit,
        commentOffset: $offset
    ) {
        status
        counter
        ResponseCode
        affectedRows {
            amountcomments
            comments {
                commentid
                postid
                parentid
                content
                createdat
                amountlikes
                isliked
                hasActiveReports
                isHiddenForUsers
                visibilityStatus
                user {
                    id
                    username
                    slug
                    img
                    isfollowed
                    isfollowing
                    isHiddenForUsers
                    visibilityStatus
                }
            }
        }
    }
}
