mutation CreateComment($action: CommentType!, $postId: ID!, $content: String!) {
    createComment(action: $action, postid: $postId, content: $content) {
        status
        counter
        ResponseCode
        affectedRows {
            commentid
            postid
            parentid
            content
            createdat
            amountlikes
            isliked
            user {
                id
                username
                slug
                img
                isfollowed
                isfollowing
            }
        }
    }
}
