query Account {
    getUserInfo {
        status
        ResponseCode
        affectedRows {
            userid
            liquidity
            invited
            amountfollowed
            amountfollower
            amountposts
            amountfriends,
            userPreferences {
                contentFilteringSeverityLevel
            }
        }
    }
}

query Profile($userid: ID) {
    getProfile(userid: $userid) {
        status
        ResponseCode
        affectedRows {
            id
            slug
            username
            img
            biography
            amountfollowed
            amountfollower
            amountposts
            amountfriends,
            isfollowed,
            isfollowing
        }
    }
}

mutation DeleteAccount($password: String!) {
    deleteAccount(password: $password) {
        status
        ResponseCode
    }
}
