query Profile($userid: ID, $contentFilterBy: ContentFilterType) {
    getProfile(userid: $userid, contentFilterBy: $contentFilterBy) {
        status
        ResponseCode
        affectedRows {
            id
            slug
            username
            img
            biography
            amountfollowed
            amountfollower
            amountposts
            amountfriends
            isfollowed
            isfollowing
            isHiddenForUsers
            hasActiveReports
            visibilityStatus
        }
    }
}

mutation DeleteAccount($password: String!) {
    deleteAccount(password: $password) {
        status
        ResponseCode
    }
}
