def isApplication = ext.has('android') && (ext.get('android') as List<String>).contains(path)
if (isApplication) {
    apply plugin: libs.plugins.androidApplication.get().pluginId
    apply plugin: libs.plugins.kotlinAndroid.get().pluginId
    apply plugin: libs.plugins.ksp.get().pluginId
} else {
    apply plugin: libs.plugins.androidLibrary.get().pluginId
    apply plugin: libs.plugins.kotlinAndroid.get().pluginId
}

def properties = new Properties()

properties.load(rootProject.file("local.properties").newDataInputStream())

def domain = properties.getProperty("peer.namespace")
if (domain == null) {
    throw RuntimeException("Application namespace not defined in $rootDir/local.properties")
}

android {
    namespace = "$domain${path.replace(':', '.')}"
    compileSdk = 35
    defaultConfig {
        minSdk = 24
        if (isApplication) {
            applicationId = "$domain${path.replace(':', '.')}"
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
