type Subscription {
  getChatMessages(chatid: ID!): AddChatmessageResponse!

  setChatMessages(chatid: ID!, content: String!): AddChatmessageResponse!
}

"""
The `ID` scalar type represents a unique identifier, often used to
refetch an object or as key for a cache. The ID type appears in a JSON
response as a String; however, it is not intended to be human-readable.
When expected as an input type, any string (such as `"4"`) or integer
(such as `4`) input value will be accepted as an ID.
"""
scalar ID

"""
The `String` scalar type represents textual data, represented as UTF-8
character sequences. The String type is most often used by GraphQL to
represent free-form human-readable text.
"""
scalar String

"""
The `Int` scalar type represents non-fractional signed whole numeric
values. Int can represent values between -(2^31) and 2^31 - 1. 
"""
scalar Int

type Query {
  hello: HelloResponse!

  searchUser(userid: ID, contentFilterBy: ContentFilterType, username: String, offset: Int, limit: Int): UserListResponse!

  listUsers(contentFilterBy: ContentFilterType, offset: Int, limit: Int): UserListResponse!

  getProfile(userid: ID, contentFilterBy: ContentFilterType, postLimit: Int): ProfileInfo!

  listFollowRelations(contentFilterBy: ContentFilterType, userid: ID, offset: Int, limit: Int): FollowRelationsResponse!

  listFriends(contentFilterBy: ContentFilterType, offset: Int, limit: Int): UserFriendsResponse!

  getUserInfo: UserInfoResponse!

  listBlockedUsers(offset: Int, limit: Int): BlockedUsersResponse!

  listPosts(filterBy: [PostFilterType!], contentFilterBy: ContentFilterType, IgnorList: IgnoreOption, sortBy: PostSortType, userid: ID, postid: ID, title: String, tag: String, from: Date, to: Date, offset: Int, limit: Int, commentOffset: Int, commentLimit: Int): PostListResponse!

  getPostInfo(postid: ID!): PostInfoResponse!

  getCommentInfo(commentId: ID!): CommentInfoResponse!

  listChildComments(parent: ID!, offset: Int, limit: Int): CommentResponse!

  listTags(offset: Int, limit: Int): TagSearchResponse!

  searchTags(tagName: String!, offset: Int, limit: Int): TagSearchResponse!

  getChat(chatid: ID!, messageOffset: Int, messageLimit: Int): ChatResponse!

  listChats(sortBy: String, from: Date, to: Date, offset: Int, limit: Int, messageOffset: Int, messageLimit: Int): ChatResponse!

  listChatMessages(chatid: ID!, offset: Int, limit: Int): AddChatmessageResponse!

  getDailyFreeStatus: GetDailyResponse!

  balance: CurrentLiquidity!

  listWinLogs(day: DayFilterType!, offset: Int, limit: Int): UserLogWins!

  listPaymentLogs(day: DayFilterType!, offset: Int, limit: Int): UserLogWins!

  getReferralInfo: ReferralInfoResponse!

  referralList(offset: Int, limit: Int): ReferralListResponse!

  listTodaysInteractions: ListTodaysInteractionsResponse!

  getActionPrices: GetActionPricesResponse!

  getTransactionHistory(type: TokenMovementFilterType, direction: DirectionFilterType, start_date: String, end_date: String, limit: Int, offset: Int, sort: SortFilterType): TransactionResponse!

  postInteractions(getOnly: GetOnly!, postOrCommentId: ID!, offset: Int, limit: Int): PostInteractionResponse
}

"""
The `Boolean` scalar type represents `true` or `false`.
"""
scalar Boolean

"""
The `Float` scalar type represents signed double-precision fractional
values as specified by
[IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point). 
"""
scalar Float

type Mutation {
  updateUserPreferences(userPreferences: UserPreferencesInput): UserPreferencesResponse!

  updateUsername(username: String!, password: String!): DefaultResponse!

  updateEmail(email: String!, password: String!): DefaultResponse!

  updatePassword(password: String!, expassword: String!): DefaultResponse!

  updateBio(biography: String!): DefaultResponse!

  updateProfileImage(img: String!): DefaultResponse!

  toggleUserFollowStatus(userid: ID!): FollowStatusResponse!

  toggleBlockUserStatus(userid: ID!): DefaultResponse!

  deleteAccount(password: String!): DefaultResponse!

  createChat(input: ChatInput!): AddChatResponse!

  updateChatInformations(input: UpdateChatInput!): AddChatResponse!

  addChatParticipants(input: ChatParticipantsInput!): AddChatResponse!

  removeChatParticipants(input: ChatParticipantsInput!): AddChatResponse!

  sendChatMessage(chatid: ID!, content: String!): AddChatmessageResponse!

  deleteChatMessage(chatid: ID!, messid: Int!): DefaultResponse!

  deleteChat(id: ID!): DefaultResponse!

  createChatFeed(input: FeedInput!): AddPostResponse!

  likeComment(commentid: ID!): DefaultResponse!

  reportComment(commentid: ID!): DefaultResponse!

  reportUser(userid: ID!): DefaultResponse!

  deletePost(id: ID!): DefaultResponse!

  createPost(action: PostType!, input: PostInput!): PostResponse!

  createComment(action: CommentType!, postid: ID!, parentid: ID, content: String!): CommentResponse!

  resolvePostAction(action: PostActionType!, postid: ID!): DefaultResponse!

  resolveTransfer(recipient: ID!, numberoftokens: Int!): DefaultResponse!
}

scalar Decimal

scalar Date

enum TokenMovementFilterType {
  TRANSACTION

  AIRDROP

  MINT

  PAYMENT

  BURN
}

enum GetOnly {
  VIEW

  LIKE

  DISLIKE

  COMMENTLIKE
}

enum DirectionFilterType {
  INCOME

  DEDUCTION
}

enum SortFilterType {
  NEWEST

  OLDEST
}

enum PostActionType {
  LIKE

  DISLIKE

  REPORT

  VIEW

  SHARE

  SAVE
}

enum PostType {
  POST
}

enum CommentType {
  COMMENT
}

enum ContentFilterType {
  MYGRANDMALIKES

  MYGRANDMAHATES
}

enum ContentType {
  image

  audio

  video

  text
}

enum PostFilterType {
  IMAGE

  AUDIO

  VIDEO

  TEXT

  FOLLOWED

  FOLLOWER

  VIEWED
}

enum IgnoreOption {
  YES

  NO
}

enum PostSortType {
  NEWEST

  TRENDING

  LIKES

  DISLIKES

  VIEWS

  COMMENTS

  FOR_ME
}

enum DayFilterType {
  D0

  D1

  D2

  D3

  D4

  D5

  W0

  M0

  Y0
}

input UserPreferencesInput {
  contentFilteringSeverityLevel: ContentFilterType
}

type Transaction {
  transactionid: String!

  transuniqueid: String!

  transactiontype: String!

  senderid: String!

  recipientid: String!

  tokenamount: Decimal!

  transferaction: String!

  message: String!

  createdat: String!
}

type TransactionResponse {
  status: String!

  responseCode: Int!

  affectedRows: [Transaction!]
}

type UserPreferences {
  contentFilteringSeverityLevel: ContentFilterType
}

type ListTodaysInteractionsResponse {
  status: String!

  ResponseCode: String

  affectedRows: TodaysInteractionsData
}

type TodaysInteractionsData {
  totalInteractions: Decimal

  totalScore: Decimal

  totalDetails: TodaysInteractionsDetailsData
}

type PostInteractionResponse {
  status: String!

  ResponseCode: String

  affectedRows: [ProfileUser!]
}

type TodaysInteractionsDetailsData {
  views: Decimal

  likes: Decimal

  dislikes: Decimal

  comments: Decimal

  viewsScore: Decimal

  likesScore: Decimal

  dislikesScore: Decimal

  commentsScore: Decimal
}

type HelloResponse {
  currentuserid: ID

  currentVersion: String

  wikiLink: String

  lastMergedPullRequestNumber: String

  companyAccountId: ID
}

type LogWins {
  from: String

  token: String

  userid: String

  postid: String

  action: String

  numbers: Decimal

  createdat: String
}

type UserLogWins {
  status: String

  counter: Int!

  ResponseCode: String

  affectedRows: [LogWins]
}

type GetDailyResponse {
  status: String!

  ResponseCode: String!

  affectedRows: [DailyFreeResponse]
}

type DailyFreeResponse {
  name: String!

  used: Int!

  available: Int!
}

type CurrentLiquidity {
  status: String!

  ResponseCode: String!

  currentliquidity: Decimal
}

type UserInfoResponse {
  status: String!

  ResponseCode: String!

  affectedRows: UserInfo
}

type UserInfo {
  userid: ID!

  liquidity: Decimal!

  amountposts: Int!

  amountblocked: Int!

  amountfollower: Int!

  amountfollowed: Int!

  amountfriends: Int!

  invited: ID!

  updatedat: Date

  userPreferences: UserPreferences
}

type PostInfoResponse {
  status: String!

  ResponseCode: String!

  affectedRows: PostInfo
}

type PostInfo {
  likes: Int!

  dislikes: Int!

  reports: Int!

  views: Int!

  saves: Int!

  shares: Int!

  comments: Int!
}

type CommentInfoResponse {
  status: String!

  ResponseCode: String!

  affectedRows: CommentInfo
}

type CommentInfo {
  likes: Int!

  reports: Int!

  comments: Int!
}

type ChatResponse {
  status: String!

  counter: Int!

  ResponseCode: String

  affectedRows: [Chat!]
}

type Chat {
  id: ID!

  image: String!

  name: String!

  createdat: Date

  updatedat: Date

  chatmessages: [ChatMessage!]!

  chatparticipants: [ChatParticipant!]!
}

type ChatMessage {
  id: ID!

  senderid: ID!

  chatid: ID!

  content: String!

  createdat: Date!
}

type ChatParticipant {
  userid: ID!

  img: String!

  username: String!

  slug: Int!

  hasaccess: Int!
}

type FollowStatusResponse {
  status: String!

  ResponseCode: String

  isfollowing: Boolean
}

type ProfilePostMedia {
  id: ID!

  title: String

  contenttype: String!

  media: String!

  createdat: String
}

type DefaultResponse {
  status: String!

  ResponseCode: String
}

type UserPreferencesResponse {
  status: String!

  ResponseCode: String

  affectedRows: UserPreferences
}

type AddPostResponse {
  status: String!

  ResponseCode: String

  affectedRows: Postinfo
}

type Postinfo {
  postid: ID!

  userid: ID!

  title: String!

  media: String!

  mediadescription: String!

  contenttype: String!
}

type AddChatResponse {
  status: String!

  ResponseCode: String

  affectedRows: Chatinfo
}

type Chatinfo {
  chatid: ID
}

type AddChatmessageResponse {
  status: String!

  counter: Int!

  ResponseCode: String

  affectedRows: [ChatMessageInfo]
}

type ChatMessageInfo {
  messid: ID

  chatid: ID

  userid: ID

  content: String

  createdat: Date
}

type BasicUserInfoResponse {
  status: String!

  ResponseCode: String

  affectedRows: BasicUserInfo
}

type BasicUserInfo {
  userid: ID

  img: String

  username: String

  slug: Int

  biography: String

  updatedat: Date!
}

type UserFriendsResponse {
  status: String!

  counter: Int!

  ResponseCode: String

  affectedRows: [BasicUserInfo]
}

type User {
  id: ID

  username: String

  status: Int

  slug: Int

  img: String

  biography: String

  createdat: Date

  updatedat: Date
}

type Profile {
  id: ID

  username: String

  status: Int

  slug: Int

  img: String

  biography: String

  isfollowed: Boolean

  isfollowing: Boolean

  amountposts: Int

  amounttrending: Int

  amountfollowed: Int

  amountfollower: Int

  amountfriends: Int

  amountblocked: Int

  imageposts: [ProfilePostMedia!]

  textposts: [ProfilePostMedia!]

  videoposts: [ProfilePostMedia!]

  audioposts: [ProfilePostMedia!]
}

type ProfileInfo {
  status: String

  ResponseCode: String

  affectedRows: Profile
}

type ProfileUser {
  id: ID!

  username: String

  slug: Int

  img: String

  isfollowed: Boolean

  isfollowing: Boolean
}

type FollowRelations {
  followers: [ProfileUser!]

  following: [ProfileUser!]
}

type FollowRelationsResponse {
  status: String

  counter: Int!

  ResponseCode: String

  affectedRows: FollowRelations
}

type BlockedUser {
  userid: String

  img: String

  username: String

  slug: Int
}

type BlockedUsers {
  iBlocked: [BlockedUser!]

  blockedBy: [BlockedUser!]
}

type BlockedUsersResponse {
  status: String

  counter: Int!

  ResponseCode: String

  affectedRows: BlockedUsers
}

type UserListResponse {
  status: String!

  counter: Int!

  ResponseCode: String

  affectedRows: [User]
}

type Tag {
  name: String!
}

type TagSearchResponse {
  status: String!

  counter: Int!

  ResponseCode: String

  affectedRows: [Tag]
}

type PostResponse {
  status: String!

  ResponseCode: String

  affectedRows: Post
}

type PostListResponse {
  status: String!

  counter: Int!

  ResponseCode: String

  affectedRows: [Post!]
}

type Post {
  id: ID!

  contenttype: String!

  title: String!

  media: String!

  cover: String!

  mediadescription: String!

  createdat: Date!

  amountlikes: Int!

  amountviews: Int!

  amountcomments: Int!

  amountdislikes: Int!

  amounttrending: Int!

  isliked: Boolean!

  isviewed: Boolean!

  isreported: Boolean!

  isdisliked: Boolean!

  issaved: Boolean!

  tags: [String]!

  user: ProfileUser!

  comments: [Comment!]!
}

type Comment {
  commentid: ID!

  userid: ID!

  postid: ID!

  parentid: ID

  content: String!

  createdat: Date!

  amountlikes: Int!

  amountreplies: Int!

  isliked: Boolean!

  user: ProfileUser!
}

type CommentResponse {
  status: String!

  counter: Int!

  ResponseCode: String

  affectedRows: [Comment]
}

type ReferralInfoResponse {
  status: String

  ResponseCode: String

  referralUuid: ID

  referralLink: String
}

type ReferralListResponse {
  status: String!

  counter: Int!

  ResponseCode: String!

  affectedRows: ReferralUsers!
}

type ReferralUsers {
  invitedBy: ProfileUser

  iInvited: [ProfileUser!]!
}

input PostInput {
  title: String!

  mediadescription: String

  contenttype: ContentType!

  media: [String!]

  cover: [String!]

  tags: [String!]
}

input ChatInput {
  name: String!

  image: String

  recipients: [String!]!
}

input UpdateChatInput {
  chatid: ID!

  name: String

  image: String
}

input ChatParticipantsInput {
  chatid: ID!

  recipients: [String!]!
}

input FeedInput {
  feedid: ID!

  title: String!

  media: String!

  mediadescription: String

  contenttype: String!
}

type ActionPriceResult {
  postPrice: Float!

  likePrice: Float!

  dislikePrice: Float!

  commentPrice: Float!
}

type GetActionPricesResponse {
  status: String!

  ResponseCode: String!

  affectedRows: ActionPriceResult!
}

"""
A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.
"""
type __Schema {
  """
  A list of all types supported by this server.
  """
  types: [__Type!]!

  """
  The type that query operations will be rooted at.
  """
  queryType: __Type!

  """
  If this server supports mutation, the type that mutation operations will be rooted at.
  """
  mutationType: __Type

  """
  If this server support subscription, the type that subscription operations will be rooted at.
  """
  subscriptionType: __Type

  """
  A list of all directives supported by this server.
  """
  directives: [__Directive!]!
}

"""
The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.

Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name and description, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.
"""
type __Type {
  kind: __TypeKind!

  name: String

  description: String

  fields(includeDeprecated: Boolean! = false): [__Field!]

  interfaces: [__Type!]

  possibleTypes: [__Type!]

  enumValues(includeDeprecated: Boolean! = false): [__EnumValue!]

  inputFields(includeDeprecated: Boolean! = false): [__InputValue!]

  ofType: __Type

  isOneOf: Boolean
}

"""
An enum describing what kind of type a given `__Type` is.
"""
enum __TypeKind {
  """
  Indicates this type is a scalar.
  """
  SCALAR

  """
  Indicates this type is an object. `fields` and `interfaces` are valid fields.
  """
  OBJECT

  """
  Indicates this type is an interface. `fields`, `interfaces`, and `possibleTypes` are valid fields.
  """
  INTERFACE

  """
  Indicates this type is a union. `possibleTypes` is a valid field.
  """
  UNION

  """
  Indicates this type is an enum. `enumValues` is a valid field.
  """
  ENUM

  """
  Indicates this type is an input object. `inputFields` is a valid field.
  """
  INPUT_OBJECT

  """
  Indicates this type is a list. `ofType` is a valid field.
  """
  LIST

  """
  Indicates this type is a non-null. `ofType` is a valid field.
  """
  NON_NULL
}

"""
Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.
"""
type __Field {
  name: String!

  description: String

  args(includeDeprecated: Boolean! = false): [__InputValue!]!

  type: __Type!

  isDeprecated: Boolean!

  deprecationReason: String
}

"""
Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.
"""
type __InputValue {
  name: String!

  description: String

  type: __Type!

  """
  A GraphQL-formatted string representing the default value for this input value.
  """
  defaultValue: String

  isDeprecated: Boolean!

  deprecationReason: String
}

"""
One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.
"""
type __EnumValue {
  name: String!

  description: String

  isDeprecated: Boolean!

  deprecationReason: String
}

"""
A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.

In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.
"""
type __Directive {
  name: String!

  description: String

  isRepeatable: Boolean!

  locations: [__DirectiveLocation!]!

  args(includeDeprecated: Boolean! = false): [__InputValue!]!
}

"""
A Directive can be adjacent to many parts of the GraphQL language, a __DirectiveLocation describes one such possible adjacencies.
"""
enum __DirectiveLocation {
  """
  Location adjacent to a query operation.
  """
  QUERY

  """
  Location adjacent to a mutation operation.
  """
  MUTATION

  """
  Location adjacent to a subscription operation.
  """
  SUBSCRIPTION

  """
  Location adjacent to a field.
  """
  FIELD

  """
  Location adjacent to a fragment definition.
  """
  FRAGMENT_DEFINITION

  """
  Location adjacent to a fragment spread.
  """
  FRAGMENT_SPREAD

  """
  Location adjacent to an inline fragment.
  """
  INLINE_FRAGMENT

  """
  Location adjacent to a variable definition.
  """
  VARIABLE_DEFINITION

  """
  Location adjacent to a schema definition.
  """
  SCHEMA

  """
  Location adjacent to a scalar definition.
  """
  SCALAR

  """
  Location adjacent to an object type definition.
  """
  OBJECT

  """
  Location adjacent to a field definition.
  """
  FIELD_DEFINITION

  """
  Location adjacent to an argument definition.
  """
  ARGUMENT_DEFINITION

  """
  Location adjacent to an interface definition.
  """
  INTERFACE

  """
  Location adjacent to a union definition.
  """
  UNION

  """
  Location adjacent to an enum definition.
  """
  ENUM

  """
  Location adjacent to an enum value definition.
  """
  ENUM_VALUE

  """
  Location adjacent to an input object type definition.
  """
  INPUT_OBJECT

  """
  Location adjacent to an input object field definition.
  """
  INPUT_FIELD_DEFINITION
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include ("Included when true." if: Boolean!) on FIELD|FRAGMENT_SPREAD|INLINE_FRAGMENT

"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip ("Skipped when true." if: Boolean!) on FIELD|FRAGMENT_SPREAD|INLINE_FRAGMENT

"""
Marks an element of a GraphQL schema as no longer supported.
"""
directive @deprecated ("Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted using the Markdown syntax, as specified by [CommonMark](https:\/\/commonmark.org\/)." reason: String = "No longer supported") on FIELD_DEFINITION|ENUM_VALUE|ARGUMENT_DEFINITION|INPUT_FIELD_DEFINITION

"""
Indicates that an Input Object is a OneOf Input Object (and thus requires exactly one of its fields be provided).
"""
directive @oneOf on INPUT_OBJECT

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
