query Getallposts(
    $filter: [PostFilterType!],
    $sort: PostSortType,
    $tag: String,
    $title: String,
    $userId: ID,
    $postId: ID,
    $contentFilterBy: ContentFilterType,
    $offset: Int,
    $limit: Int
) {
    listPosts(
        filterBy: $filter,
        sortBy: $sort,
        tag: $tag,
        title: $title,
        userid: $userId,
        postid: $postId,
        contentFilterBy: $contentFilterBy,
        limit: $limit,
        offset: $offset
    ) {
        status
        counter
        ResponseCode
        affectedRows {
            id
            title
            mediadescription
            isliked
            isviewed
            isdisliked
            amountlikes
            amountdislikes
            amountviews
            amountcomments
            media
            cover
            isreported
            isHiddenForUsers
            visibilityStatus
            contenttype
            createdat
            url
            user {
                id
                username
                slug
                img
                isfollowed
                isfollowing
                isHiddenForUsers
                visibilityStatus
            }
        }
    }
}
