mutation CreatePost(
    $action: PostenType!,
    $title: String!,
    $description: String,
    $type: ContenType,
    $media: [String!],
    $cover: [String!],
    $tags: [String!],
) {
    createPost(action: $action, input: {
        title: $title,
        mediadescription: $description,
        contenttype: $type,
        media: $media,
        cover: $cover,
        tags: $tags }
    ) {
        status
        ResponseCode
        affectedRows {
            id
            title
            mediadescription
            isliked
            isviewed
            isdisliked
            amountlikes
            amountdislikes
            amountviews
            amountcomments
            media
            cover
            createdat
        }
    }
}

