mutation CreatePost(
    $action: PostType!,
    $title: String!,
    $description: String,
    $contentType: ContentType!,
    $uploadedFiles: String,
    $cover: [String!],
    $tags: [String!],
) {
    createPost(action: $action, input: {
        title: $title,
        mediadescription: $description,
        contenttype: $contentType,
        uploadedFiles: $uploadedFiles,
        cover: $cover,
        tags: $tags },
    ) {
        status
        ResponseCode
        affectedRows {
            id
            title
            mediadescription
            isliked
            isviewed
            isdisliked
            amountlikes
            amountdislikes
            amountviews
            amountcomments
            media
            cover
            contenttype
            createdat
            url
            user {
                id
                username
                slug
                img
                isfollowed
                isfollowing
            }
        }
    }
}
