query ListFollowingsRelations(
    $userid: ID!,
    $contentFilterBy: ContentFilterType,
    $offset: Int!,
    $limit: Int!
) {
    listFollowRelations(
        userid: $userid,
        contentFilterBy: $contentFilterBy,
        offset: $offset,
        limit: $limit
    ) {
        status
        counter
        ResponseCode
        affectedRows {
            following {
                id
                username
                slug
                img
                isfollowed
                isfollowing
                isHiddenForUsers
                visibilityStatus
            }
        }
    }
}
